# Site settings
title: Open Source Weekends
email: osweekends@gmail.com
twitter: https://twitter.com/os_weekends
facebook: https://www.facebook.com/osweekends
github: https://github.com/OSWeekends
url: http://osweekends.com
meetup: https://www.meetup.com/Open-Source-Weekends/
description: "OpenSource Weekends es un Meetup mensual donde cualquiera, incluso sin conocimientos, puede promover y contribuir con el Software Libre"
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
sass:
  style: :compressed
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate