# Site settings
title: OpenSource Weekends
email: osweekends@gmail.com
twitter: https://twitter.com/os_weekends
github: https://github.com/OSWeekends
url: http://osweekends.github.com
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
sass:
  style: :compressed
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate